.travis.yml, README.md
1. 添加 codecov 配置
2. README.md 中添加 codecov badage
=> 添加 codecov 配置

jest.config.js, package.json, src/@types/index.d.ts, src/components/Avatar/__test__/index.test.tsx, src/components/Button/__test__/index.test.tsx, src/components/Card/__test__/index.test.tsx, src/components/Icon/__test__/index.test.tsx, src/components/Loading/__test__/index.test.tsx, src/components/Menu/SubMenu.tsx, src/components/Message/__test__/index.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Popover/PopoverContent.tsx, src/components/Scroll/Scroll.md, src/components/Scroll/Scroll.tsx, src/components/Scroll/__test__/__snapshots__/index.test.tsx.snap, src/components/Scroll/__test__/index.test.tsx, src/components/Scroll/index.ts, src/components/Scroll/stories/Scroll.stories.tsx, src/components/Scroll/stories/style.scss, src/components/Table/Table.tsx, src/components/Table/TableHeader.tsx, src/components/Tabs/__test__/index.test.tsx, src/components/index.ts, src/components/message/__test__/index.test.tsx, src/components/notification/__test__/index.test.tsx, src/setupTests.ts, src/styles/index.scss, src/styles/scroll.scss, src/utils/classnames.ts, tsconfig.json
在做首页大屏展示图片的时候，需要提供一个滚动条，这个滚动条需要知道页面每个部分滚动的位置，所以提取了这个Scroll组件
新增 scroll 组件
- 提供监测子内容距离顶部的组件，提供页面变换时的页数回调
=> Add scroll 组件

README.md, scripts/new-component.sh
更新快速新建组件脚本内容
eg:
```
yarn new Chart
```
生成内容
=> ♻️ (new scripts) update the new script

src/components/Message/Message.tsx, src/components/Message/message.tsx, src/components/index.ts, src/components/message/message.tsx, src/components/notification/notification.tsx
1. 解决 tsconfig paths 不被编译的问题
https://github.com/microsoft/TypeScript/issues/10866
2. Message 重命名为 message
=> 解决 tsconfig paths 不被编译的问题

src/components/Button/Button.tsx, src/components/Grid/Col.tsx, src/components/Grid/Row.tsx, src/components/Guidance/Step.tsx, src/components/PurePortal/PurePortal.tsx
1. 修复 Button, Col, Row, Guidance, PurePortal 组件 state 类型错误的 bug
=> 🐛 (state type) 修复 Button, Col, Row, Guidance, PurePortal 组件 state 类型错误

src/styles/question.scss
=> 🐛 (Question style) 修复 Question 组件没有样式的 bug

src/components/Input/Input.tsx, src/components/Input/TextArea.tsx, src/components/Switch/Switch.tsx
更改Lodash的调用方式，减少外部App build时的bundle size
=> update import lodash way to reduce the bundle size

src/components/Button/Button.tsx, src/components/Button/__test__/__snapshots__/index.test.tsx.snap, src/components/Button/stories/Button.stories.tsx, src/styles/button.scss
PS:  Button根据设计师尺寸做了调整，请注意引用Button的样式是否存在问题
=> 💄 button 添加shape: round, circle, square , type: dashed,golden

src/components/Search/README.md, src/components/Search/Search.tsx, src/components/Search/index.ts, src/components/Search/stories/Search.stories.tsx, src/components/Search/stories/style.scss, src/styles/option.scss, src/styles/search.scss, src/styles/select.scss, src/styles/selection.scss
=> ✨ (Optimize) 优化 Search 组件

src/components/notification/Content.tsx, src/components/notification/README.md, src/components/notification/__test__/index.test.tsx, src/components/notification/interface.tsx, src/components/notification/notification.tsx, src/components/notification/stories/notification.stories.tsx, src/styles/notification.scss
=> 添加 notificaton.default(config)

jest.config.js, package.json, src/components/PurePortal/PurePortal.tsx, src/components/PurePortal/__test__/index.test.tsx, src/components/notification/Content.tsx, src/components/notification/README.md, src/components/notification/__test__/__snapshots__/index.test.tsx.snap, src/components/notification/__test__/index.test.tsx, src/components/notification/notification.tsx, src/components/notification/stories/notification.stories.tsx, src/hoc/__test__/index.test.tsx, src/hoc/utils.ts, src/hoc/withCreateNotificationContainer.tsx, src/styles/notification.scss, src/utils/NotificationContainer.tsx, yarn.lock
=> 添加 notification jsx 的调用形式

package.json, src/components/Row/Col.tsx, src/components/Row/README.md, src/components/Row/Row.tsx, src/components/Row/stories/Row.stories.tsx, yarn.lock
=> Row 组件添加 gutter 属性

src/components/Drawer/Drawer.tsx, src/components/Popup/Popup.tsx, src/components/Portal/Portal.tsx, src/components/PurePortal/PurePortal.tsx
=> 修复运行 npm run build:ts 时报错的 bug

src/components/Row/Row.tsx
=> 🐛 (Row) 修复 Row 服务端渲染时报错的 bug

src/components/Modal/Modal.tsx
=> 🐛 (Modal) 修复 Modal footer  显示不正确的 bug

src/components/notification/Content.tsx, src/styles/notification.scss
=> notification功能修改

src/components/Tabs/Tabs.tsx
=> ✨ (Tabs) Tabs.TabPanel 组件添加可以修改 className 和 style 的功能

src/components/Select/Select.tsx
delete unmountOnExit props from Select
=> 🐛 (bug) 修复 Select 组件  unmountOnExit

src/components/Modal/__test__/__snapshots__/index.test.tsx.snap, src/components/message/README.md, src/components/message/message.tsx, src/components/message/stories/message.stories.tsx
=> ✨ (message) message 组件添加直接传字符串的功能

src/components/Modal/__test__/__snapshots__/index.test.tsx.snap, src/components/message/Content.tsx
=> ✨ (message) 添加 message 组件当鼠标 hover 在其上时，不会消失的功能

src/components/Select/Select.tsx, src/components/Select/stories/Select.stories.tsx, src/components/Selection/Option.tsx
=> 🐛 (bug) 修复select 组件默认值问题
